---
function:
  name: omni-dw-project44-ltl-location-update-${self:provider.stage}
  handler: src/realtime/ltlUpdates/p44_ltl_location_updates.handler
  memorySize: 1024
  timeout: 300
  runtime: nodejs20.x
  tags:
    Name: omni-dw-project44-location-ltl-update-${self:provider.stage}
  layers:
    - { Ref: P44RtLambdaLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/realtime/ltlUpdates/p44_ltl_location_updates.js"
      - "src/shared/**"
  events:
    - sqs:
        arn: ${ssm:/${self:service}/${self:provider.stage}/ltl-location-update-queue-arn}

  environment:      
    REFERENCES_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/references/ddb.tableName~true} 
    SHIPMENT_HEADER_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName~true}
    P44_LOCATION_LOGS_TABLE_NAME: ${ssm:/${self:service}/${self:provider.stage}/ltl-location-update-log-table-name}
    REFERENCES_ORDERNO_INDEX: ${ssm:/${self:service}/${self:provider.stage}/references/ddb.orderNoIndex}
    P44_LTL_LOCATION_UPDATES_API: ${ssm:/${var.application}/${self:provider.stage}/ltl-location-update/api.url}      
    P44_CLIENT_ID: ${ssm:/omni-p44-rt-updates/${self:provider.stage}/p44-credentials/clientId}
    P44_CLIENT_SECRET: ${ssm:/omni-p44-rt-updates/${self:provider.stage}/p44-credentials/clientSecret}
    P44_AUTH_API: ${ssm:/omni-p44-rt-updates/${self:provider.stage}/authApi.url}
    MCKESSON_CUSTOMER_NUMBERS: ${ssm:/omni-p44-rt-updates/${self:provider.stage}/mckesson-customer/numbers}
    MCKESSON_CUSTOMER_NAME : ${ssm:/omni-p44-rt-updates/${self:provider.stage}/mckesson-customer/name}
    TIME_ZONE_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/timezone-master/ddb.tableName~true}
    GOOGLE_API_KEY: ${ssm:/omni-ivia/${self:provider.stage}/google/api.Key~true}
