OmniDwP44TlUpdateTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-dw-p44-tl-update-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "UUID"
        AttributeType: "S"
      - AttributeName: "ReferenceNo"
        AttributeType: "S"
      - AttributeName: "FK_OrderNo"
        AttributeType: "S"
      - AttributeName: "StatusCode"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "UUID"
        KeyType: "HASH"
      - AttributeName: "ReferenceNo"
        KeyType: "RANGE"
    GlobalSecondaryIndexes:
      - IndexName: "FK_OrderNo-StatusCode-Index"
        KeySchema:
          - AttributeName: "FK_OrderNo"
            KeyType: "HASH"
          - AttributeName: "StatusCode"
            KeyType: "RANGE"
        Projection:
          ProjectionType: ALL
