---
function:
  name: omni-dw-project44-milestone-update-${self:provider.stage}
  handler: src/realtime/p44_milestone_updates.handler
  memorySize: 1024
  timeout: 90
  
  layers:
    - { Ref: P44RtLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/realtime/p44_milestone_updates.js"
      - "src/shared/**"
  events:
    - sqs:
        arn: { "Fn::GetAtt": ["P44TargetQueue", "Arn"] }
        batchSize: 10
        functionResponseType: ReportBatchItemFailures

  environment:      
    TRACKING_NOTES_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/tracking-notes/ddb.tableName~true}
    REFERENCES_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/references/ddb.tableName~true} 
    SHIPMENT_HEADER_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName~true}
    P44_MILESTONE_LOGS_TABLE_NAME: ${ssm:/omni-p44-rt-updates/${self:provider.stage}/milestone-update/ddb.tableName~true}
    MCKESSON_CUSTOMER_NUMBERS: ${ssm:/omni-p44-rt-updates/${self:provider.stage}/mckesson-customer/numbers}